'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(n);
const fmt=s=>new Date(s.slice(0,10)+'T12:00:00Z').toLocaleDateString('vi-VN',{timeZone:'UTC'});
const iso=d=>d.toISOString().slice(0,10),add=(s,n)=>{let d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return iso(d)};
const duration=n=>{n=Math.round(n);return `${Math.floor(n/60)} giờ${n%60?' '+number(n%60)+' phút':''}`};
let data,weeks=[];
try{const seed=$('initial-data');if(seed)data=JSON.parse(seed.textContent)}catch{}
for(let d='2025-12-29';d<'2027-01-01';d=add(d,7))weeks.push({from:d,to:add(d,6)});
function monthRange(){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());if(!today.startsWith('2026-'))return ['2026-01-01','2026-12-31'];const start=today.slice(0,7)+'-01',d=new Date(start+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);d.setUTCDate(0);return [start,iso(d)]}
function validDate(d){return /^2026-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d))&&d>='2026-01-01'&&d<='2026-12-31'}
const tablePages={summary:{page:1,key:'',rows:[]},titleanalysis:{page:1,key:'',rows:[]}};
function paginateTable(id){const state=tablePages[id],body=$(id),key=body.innerHTML;if(state.key!==key){state.page=1;state.key=key}state.rows=[...body.rows].map(r=>r.outerHTML);paintTablePage(id)}
function paintTablePage(id){const state=tablePages[id],total=state.rows.length,pages=Math.max(1,Math.ceil(total/7));state.page=Math.max(1,Math.min(pages,state.page));$(id).innerHTML=state.rows.slice((state.page-1)*7,state.page*7).join('');let nav=$(id+'pages');if(!nav){nav=document.createElement('nav');nav.id=id+'pages';nav.className='pagination';nav.setAttribute('aria-label',id==='summary'?'Trang tổng hợp nhóm':'Trang nội dung họp');$(id).closest('.tablewrap').after(nav);nav.addEventListener('click',e=>{const button=e.target.closest('[data-page]');if(!button)return;state.page=+button.dataset.page;paintTablePage(id)})}nav.hidden=pages<=1;nav.innerHTML=`<span>${(state.page-1)*7+1}–${Math.min(total,state.page*7)} / ${total}</span><button data-page="${state.page-1}" ${state.page===1?'disabled':''}>Trước</button>`+Array.from({length:pages},(_,i)=>`<button data-page="${i+1}" ${state.page===i+1?'aria-current="page"':''}>${i+1}</button>`).join('')+`<button data-page="${state.page+1}" ${state.page===pages?'disabled':''}>Sau</button>`}
function refreshGroupOptions(){const markup='<option value="">Tất cả nhóm</option>'+[...new Set(data.records.map(r=>r.group))].sort().map(g=>`<option value="${esc(g)}">${esc(g)}</option>`).join('');for(const id of ['group','trendgroup','titlegroup','calgroup','barsgroup','summarygroup']){const selected=$(id).value;$(id).innerHTML=markup;$(id).value=selected}}
function options(){const [start,end]=monthRange();$('from').value=start;$('to').value=end;$('trendfrom').value=start;$('trendto').value=end;refreshGroupOptions()}
function sectionGroups(id){const start=$('from').value,end=$('to').value,group=$(id).value,records=data.records.filter(r=>r.from.slice(0,10)>=start&&r.from.slice(0,10)<=end&&(!group||r.group===group));return grouped(records).map(g=>({...g,kind:records.find(r=>r.group===g.name).kind})).sort((a,b)=>b.minutes-a.minutes)}
function render(){const start=$('from').value,end=$('to').value;if(!validDate(start)||!validDate(end)||start>end){$('range').textContent='Vui lòng chọn khoảng ngày hợp lệ trong năm 2026.';return}const fi=weeks.findIndex(w=>start>=w.from&&start<=w.to),ti=weeks.findIndex(w=>end>=w.from&&end<=w.to);
const records=data.records.filter(x=>x.from.slice(0,10)>=start&&x.from.slice(0,10)<=end&&(!$('group').value||x.group===$('group').value));const aggregates=new Map();for(const r of records){if(!aggregates.has(r.group))aggregates.set(r.group,{name:r.group,kind:r.kind,count:0,minutes:0});let a=aggregates.get(r.group);a.count++;a.minutes+=r.minutes}let groups=[...aggregates.values()].sort((a,b)=>b.minutes-a.minutes);let total=records.reduce((s,r)=>s+r.minutes,0);
renderDaily(records,fi,ti);renderTitles();
$('range').textContent=`Tuần ${fi+1} – Tuần ${ti+1} · ${fmt(start)} – ${fmt(end)} · ${ti-fi+1} tuần · ${$('group').value||'Tất cả nhóm'}`;$('count').textContent=number(records.length);$('hours').textContent=number(total/60)+' giờ';$('groups').textContent=groups.filter(g=>!['Chưa xác định','UII / USI'].includes(g.name)).length;$('unknown').textContent=records.filter(r=>r.group==='Chưa xác định').length;
const barGroups=sectionGroups('barsgroup'),summaryGroups=sectionGroups('summarygroup');let max=barGroups[0]?.minutes||1;$('bars').innerHTML=barGroups.length?barGroups.map(g=>`<div class="bar ${['Chưa xác định','UII / USI'].includes(g.name)?'muted':''}"><span>${esc(g.name)}</span><div class="track"><div class="fill" style="width:${g.minutes/max*100}%"></div></div><b>${number(g.minutes/60)}</b></div>`).join(''):'<p class="empty">Không có lịch phù hợp với bộ lọc.</p>';
$('summaryCount').textContent=summaryGroups.length+' nhóm';$('summary').innerHTML=summaryGroups.length?summaryGroups.map(g=>`<tr><td><b>${esc(g.name)}</b></td><td><span class="pill ${g.kind!=='Dự án / tổ chức'?'gray':''}">${esc(g.kind)}</span></td><td>${g.count}</td><td>${number(g.minutes/60)}</td><td>${duration(g.minutes/g.count)}</td></tr>`).join(''):'<tr><td colspan="5">Không có lịch trong khoảng đã chọn.</td></tr>';
paginateTable('summary');renderTrend();updateDateButtons();
}
let chartState={key:'',start:0,size:0,selected:null};
function chartData(){const start=$('trendfrom').value,end=$('trendto').value;if(!validDate(start)||!validDate(end)||start>end)return null;const fi=weeks.findIndex(w=>start>=w.from&&start<=w.to),ti=weeks.findIndex(w=>end>=w.from&&end<=w.to);return {start,end,fi,ti,records:data.records.filter(r=>r.from.slice(0,10)>=start&&r.from.slice(0,10)<=end&&(!$('trendgroup').value||r.group===$('trendgroup').value))}}
function renderTrend(){const model=chartData();if(!model){$('trendrange').textContent='Vui lòng chọn khoảng ngày hợp lệ trong năm 2026.';$('trend').innerHTML='';$('trenddetails').innerHTML='';return}const {start,end,fi,ti,records}=model,key=start+end+$('trendgroup').value,n=ti-fi+1;if(chartState.key!==key){chartState={key,start:fi,size:n,selected:null}}chartState.size=Math.min(n,Math.max(1,chartState.size));chartState.start=Math.max(fi,Math.min(ti-chartState.size+1,chartState.start));
const startWeek=chartState.start,lastWeek=startWeek+chartState.size-1;const selectedWeeks=weeks.slice(startWeek,lastWeek+1);const values=selectedWeeks.map(w=>records.filter(r=>r.from.slice(0,10)>=w.from&&r.from.slice(0,10)<=w.to).reduce((s,r)=>s+r.minutes/60,0));const peak=Math.max(...values,1),W=620,H=270,left=42,bottom=217,top=22,step=(W-left-12)/values.length;
$('trendrange').textContent=`${fmt(start)} – ${fmt(end)} · Tuần ${fi+1} – Tuần ${ti+1} · ${$('trendgroup').value||'Tất cả nhóm'} · ${records.length} lượt · ${duration(records.reduce((n,r)=>n+r.minutes,0))}`;$('zoomlabel').textContent=`Đang xem Tuần ${startWeek+1}–${lastWeek+1}`;$('zoomout').disabled=chartState.size===n;$('zoomin').disabled=chartState.size===1;$('panleft').disabled=startWeek===fi;$('panright').disabled=lastWeek===ti;
let svg=`<svg viewBox="0 0 ${W} ${H}" role="group" aria-label="Giờ đặt phòng theo tuần. Cuộn trên cột để phóng to, bấm để xem chi tiết.">`;
for(let i=0;i<=4;i++){const y=bottom-(bottom-top)*i/4;svg+=`<line x1="${left}" y1="${y}" x2="608" y2="${y}" stroke="#dfe8ed"/><text x="34" y="${y+4}" text-anchor="end" fill="#6b7d88" font-size="12">${number(peak*i/4)}</text>`}
values.forEach((v,i)=>{const index=startWeek+i,w=weeks[index],rs=records.filter(r=>r.from.slice(0,10)>=w.from&&r.from.slice(0,10)<=w.to),height=v/peak*(bottom-top),x=left+i*step+step*.16;svg+=`<g data-week="${index}" tabindex="0" role="button" aria-label="Tuần ${index+1}, ${rs.length} lượt, ${duration(v*60)}"><rect x="${left+i*step}" y="${top}" width="${step}" height="${bottom-top+10}" fill="transparent"/><rect x="${x}" y="${bottom-Math.max(height,3)}" width="${Math.max(2,step*.68)}" height="${Math.max(height,3)}" fill="${chartState.selected===index?'#dc9f2c':v?'#087f8b':'#d9e3e8'}" rx="3"/><title>Tuần ${index+1}: ${rs.length} lượt · ${duration(v*60)}</title></g>`;if(i===0||i===values.length-1||i%Math.max(1,Math.ceil(values.length/7))===0)svg+=`<text x="${x+step*.34}" y="241" font-size="12" fill="#58717e" text-anchor="middle">T${index+1}</text>`;if(values.length<=10)svg+=`<text x="${x+step*.34}" y="${bottom-Math.max(height,3)-7}" font-size="12" fill="#305362" text-anchor="middle">${number(v)}</text>`});$('trend').innerHTML=svg+'</svg>';if(chartState.selected!=null)showTrendDetails(chartState.selected);else $('trenddetails').innerHTML='<p class="empty">Chọn một cột để xem lịch và các nhóm sử dụng trong tuần.</p>';updateDateButtons()}
function showTrendDetails(index){chartState.selected=index;$('trend').querySelectorAll('[data-week]').forEach(g=>{const selected=+g.dataset.week===index;g.setAttribute('aria-pressed',String(selected));const bar=g.querySelectorAll('rect')[1];bar.setAttribute('fill',selected?'#dc9f2c':Number(bar.getAttribute('height'))>3?'#087f8b':'#d9e3e8')});const model=chartData();if(!model)return;const w=weeks[index],rs=model.records.filter(r=>r.from.slice(0,10)>=w.from&&r.from.slice(0,10)<=w.to),minutes=rs.reduce((s,r)=>s+r.minutes,0),byday=daynames.map((name,i)=>({name,count:rs.filter(r=>dayIndex(r.from)===i).length})),max=Math.max(0,...byday.map(d=>d.count));$('trenddetails').innerHTML=`<div class="trenddetailhead"><h3>${weekLabel(index)}</h3><span>${rs.length} lượt · ${duration(minutes)} · ${grouped(rs).length} nhóm</span></div><p class="trenddetaillead">${max?'Đặt nhiều nhất: '+byday.filter(d=>d.count===max).map(d=>d.name).join(' / ')+' ('+max+' lượt mỗi ngày).':'Tuần này chưa có lịch trong khoảng đã chọn.'}</p>${groupList(rs)}${rs.length?`<details class="trendlist"><summary>Xem ${rs.length} lịch: tiêu đề, nhóm, người đặt và giờ</summary><div class="tablewrap"><table><thead><tr><th>Ngày / giờ</th><th>Nhóm & người đặt</th><th>Nội dung</th><th>Thời lượng</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${fmt(r.from)}<br>${r.from.slice(11,16)}–${r.to.slice(11,16)}</td><td>${esc(r.group)}<br><small>${esc(r.booker||r.host)}</small></td><td><button class="detailsbutton" data-id="${r.id}">${esc(r.title)}</button></td><td>${duration(r.minutes)}</td></tr>`).join('')}</tbody></table></div></details>`:''}`}
function zoomChart(direction,anchor){const m=chartData();if(!m)return;const n=m.ti-m.fi+1,old=chartState.size;const size=direction>0?Math.max(1,Math.floor(old/1.6)):Math.min(n,Math.max(old+1,Math.ceil(old*1.6)));const center=anchor??chartState.start+Math.floor(old/2);chartState.size=size;chartState.start=Math.max(m.fi,Math.min(m.ti-size+1,center-Math.floor(size/2)));chartState.selected=center;renderTrend()}
$('trend').addEventListener('wheel',e=>{const g=e.target.closest('[data-week]');if(!g)return;e.preventDefault();zoomChart(e.deltaY<0?1:-1,+g.dataset.week)},{passive:false});for(const type of ['click','focusin'])$('trend').addEventListener(type,e=>{const g=e.target.closest('[data-week]');if(g)showTrendDetails(+g.dataset.week)});$('trend').addEventListener('keydown',e=>{const g=e.target.closest('[data-week]');if(g&&['Enter',' '].includes(e.key)){e.preventDefault();showTrendDetails(+g.dataset.week)}});$('trenddetails').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)openDetail(b.dataset.id)});
$('zoomin').onclick=()=>zoomChart(1);$('zoomout').onclick=()=>zoomChart(-1);$('zoomreset').onclick=()=>{chartState.key='';renderTrend()};$('panleft').onclick=()=>{chartState.start-=Math.max(1,Math.floor(chartState.size/2));renderTrend()};$('panright').onclick=()=>{chartState.start+=Math.max(1,Math.floor(chartState.size/2));renderTrend()};

const daynames=['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ nhật'];
const dayIndex=s=>(new Date(s.slice(0,10)+'T12:00:00Z').getUTCDay()+6)%7;
const weekLabel=i=>`Tuần ${i+1} · ${fmt(weeks[i].from)} – ${fmt(weeks[i].to)}`;
const groupColors={'ONTO':'#915332','Edtronaut':'#087e8b','Affic AI':'#5656a3','UII / USI':'#526778','Chưa xác định':'#687b84','SGA':'#ad6924'};
function grouped(rs){const map=new Map();for(const r of rs){const v=map.get(r.group)||{name:r.group,count:0,minutes:0};v.count++;v.minutes+=r.minutes;map.set(r.group,v)}return [...map.values()].sort((a,b)=>b.count-a.count||b.minutes-a.minutes)}
function groupList(rs){return grouped(rs).map(g=>`<div class="groupday"><b>${esc(g.name)}</b><span>${g.count} lượt · ${duration(g.minutes)}</span></div>`).join('')}
function leading(rs){const g=grouped(rs);return g.length?g.filter(x=>x.count===g[0].count).map(x=>`${esc(x.name)} (${x.count} lượt)`).join(', '):'Không có lịch'}
function renderDaily(records,fi,ti){
 const buckets=daynames.map((name,i)=>({name,records:records.filter(r=>dayIndex(r.from)===i)}));
 const maxCount=Math.max(0,...buckets.map(b=>b.records.length)),maxMinutes=Math.max(0,...buckets.map(b=>b.records.reduce((s,r)=>s+r.minutes,0)));
 const countWinners=buckets.filter(b=>b.records.length===maxCount),hourWinners=buckets.filter(b=>b.records.reduce((s,r)=>s+r.minutes,0)===maxMinutes);
 const dates=new Map();for(const r of records){const d=r.from.slice(0,10);if(!dates.has(d))dates.set(d,[]);dates.get(d).push(r)}const maxDate=Math.max(0,...[...dates.values()].map(a=>a.length));const dateWinners=[...dates].filter(([d,rs])=>rs.length===maxDate).sort(([a],[b])=>a.localeCompare(b));
 $('dayinsights').innerHTML=records.length?`<article><span>Thứ có nhiều lượt nhất</span><strong>${countWinners.map(b=>b.name).join(' / ')}</strong><p>${maxCount} lượt${countWinners.length>1?' mỗi thứ · đồng hạng':''} trong khoảng đã chọn</p></article><article><span>Thứ có tổng giờ cao nhất</span><strong>${hourWinners.map(b=>b.name).join(' / ')}</strong><p>${duration(maxMinutes)}${hourWinners.length>1?' mỗi thứ · đồng hạng':''}</p></article><article><span>Ngày cụ thể nhiều lượt nhất</span><strong>${maxDate} lượt / ngày</strong><div class="datewinners">${dateWinners.map(([d,rs])=>{const w=weeks.findIndex(w=>d>=w.from&&d<=w.to);return `<button class="datewinner" data-week="${w}">${daynames[dayIndex(d)]}, ${fmt(d)}<small>${leading(rs)}</small></button>`}).join('')}</div></article>`:'<p class="empty">Không có lịch trong khoảng đã chọn.</p>';
 $('weekdaystats').innerHTML=buckets.map(b=>{const minutes=b.records.reduce((s,r)=>s+r.minutes,0);return `<article class="weekday ${maxCount&&b.records.length===maxCount?'topday':''}"><h3>${b.name}</h3><strong>${b.records.length}<small> lượt</small></strong><div class="track"><div class="fill" style="width:${maxCount?b.records.length/maxCount*100:0}%"></div></div><p>${duration(minutes)}</p><span class="dayleader">${leading(b.records)}</span>${b.records.length?`<details><summary>Xem ${grouped(b.records).length} nhóm</summary>${groupList(b.records)}</details>`:''}</article>`}).join('');
 const calendarRecords=data.records.filter(r=>!$('calgroup').value||r.group===$('calgroup').value);fi=0;ti=weeks.length-1;
 const previous=+$('focusweek').value;const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const current=weeks.findIndex(w=>today>=w.from&&today<=w.to);
 let focused=$('focusweek').value!==''&&previous>=fi&&previous<=ti?previous:current>=fi&&current<=ti?current:fi;
 $('focusweek').innerHTML=weeks.slice(fi,ti+1).map((w,j)=>`<option value="${fi+j}">${weekLabel(fi+j)}</option>`).join('');$('focusweek').value=String(focused);$('prevweek').disabled=focused===fi;$('nextweek').disabled=focused===ti;
 const w=weeks[focused];if(!validDate($('caldate').value)||$('caldate').value<w.from||$('caldate').value>w.to){$('caldate').value=today>=w.from&&today<=w.to&&validDate(today)?today:w.from<'2026-01-01'?'2026-01-01':w.from}const weekRecords=calendarRecords.filter(r=>r.from.slice(0,10)>=w.from&&r.from.slice(0,10)<=w.to);const weekDays=daynames.map((name,i)=>{let date=add(w.from,i);return {name,date,records:weekRecords.filter(r=>r.from.slice(0,10)===date).sort((a,b)=>a.from.localeCompare(b.from))}});const most=Math.max(0,...weekDays.map(d=>d.records.length));const weekMinutes=weekRecords.reduce((s,r)=>s+r.minutes,0);
 $('weekdescription').textContent=weekLabel(focused)+' · '+($('calgroup').value||'Tất cả nhóm');$('weekstats').innerHTML=`<span><b>${weekRecords.length}</b> lượt đặt</span><span><b>${duration(weekMinutes)}</b> tổng thời lượng</span><span><b>${weekDays.filter(d=>d.records.length).length}</b> ngày có lịch</span><span>${most?`Đặt nhiều nhất: <b>${weekDays.filter(d=>d.records.length===most).map(d=>d.name).join(' / ')}</b> (${most} lượt${weekDays.filter(d=>d.records.length===most).length>1?' mỗi ngày':''})`:'Tuần này chưa có lịch phù hợp'}</span>`;
 $('weekcalendar').innerHTML=weekDays.map(d=>{let outside=d.date<'2026-01-01'||d.date>'2026-12-31';return `<article class="calday ${outside?'outside':''} ${d.date===$('caldate').value?'selecteddate':''} ${most&&d.records.length===most?'topday':''}"><div class="calhead"><h3>${d.name}</h3><span>${fmt(d.date)}</span>${most&&d.records.length===most?'<small class="mostbadge">Nhiều lượt nhất</small>':''}</div><div class="caltotal">${d.records.length} lượt <span>· ${duration(d.records.reduce((s,r)=>s+r.minutes,0))}</span></div><div class="daybookings">${d.records.length?d.records.map(r=>`<button class="daybooking" data-id="${r.id}" style="--group-color:${groupColors[r.group]||'#40775e'}"><span class="bookingtime">${r.from.slice(11,16)} – ${r.to.slice(11,16)}</span><b>${esc(r.group)}</b><span class="bookingtitle">${esc(r.title)}</span><span class="bookingperson">Người đặt: ${esc(r.booker||'Chưa ghi rõ')}</span><small>${duration(r.minutes)}</small></button>`).join(''):`<p class="nobooking">${outside?'Ngoài năm 2026':'Chưa có lịch đặt'}</p>`}</div></article>`}).join('');
}
$('caldate').onchange=()=>{const d=$('caldate').value;if(!validDate(d))return;$('focusweek').value=String(weeks.findIndex(w=>d>=w.from&&d<=w.to));render()};$('focusweek').onchange=()=>{$('caldate').value='';render()};$('prevweek').onclick=()=>{$('focusweek').value=String(+$('focusweek').value-1);render()};$('nextweek').onclick=()=>{$('focusweek').value=String(+$('focusweek').value+1);render()};
$('weekcalendar').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)openDetail(b.dataset.id)});$('dayinsights').addEventListener('click',e=>{const b=e.target.closest('[data-week]');if(b){$('focusweek').value=b.dataset.week;render();$('weekcalendar').scrollIntoView({behavior:'smooth',block:'start'})}});

function openDetail(id){const r=data.records.find(r=>r.id===id);if(!r)return;$('mtitle').textContent=r.title;$('mbody').innerHTML=`<dl><dt>Nhóm</dt><dd>${esc(r.group)}</dd><dt>Người đặt</dt><dd>${esc(r.booker||'Không ghi trong lịch')}</dd><dt>Ngày</dt><dd>${fmt(r.from)}</dd><dt>Khung giờ</dt><dd>${r.from.slice(11,16)} – ${r.to.slice(11,16)}</dd><dt>Thời lượng</dt><dd>${duration(r.minutes)}</dd><dt>Người chủ trì</dt><dd>${esc(r.host||'Không ghi trong lịch')}</dd><dt>Nội dung</dt><dd>${esc(r.description||'Không có mô tả thêm')}</dd><dt>Cách nhận diện</dt><dd>${esc(r.basis)}</dd><dt>Mã lịch nguồn</dt><dd>${esc(r.id)}</dd></dl>`;$('modal').showModal()}
$('close').onclick=()=>$('modal').close();$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const b=$('modal').getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)$('modal').close()}});
for(const id of ['from','to','group'])$(id).onchange=()=>{if(id==='from'&&$('from').value>$('to').value)$('to').value=$('from').value;if(id==='to'&&$('to').value<$('from').value)$('from').value=$('to').value;render()};
for(const id of ['trendfrom','trendto'])$(id).onchange=()=>{if(id==='trendfrom'&&$('trendfrom').value>$('trendto').value)$('trendto').value=$('trendfrom').value;if(id==='trendto'&&$('trendto').value<$('trendfrom').value)$('trendfrom').value=$('trendto').value;renderTrend()};
$('reset').onclick=()=>{$('from').value='2026-01-01';$('to').value='2026-12-31';$('group').value='';render()};$('thismonth').onclick=()=>{const [a,b]=monthRange();$('from').value=a;$('to').value=b;render()};
let picker={target:null,month:0,returnTo:null};
function updateDateButtons(){for(const id of ['from','to','caldate','trendfrom','trendto']){const button=$(id+'display');if(button)button.innerHTML=`<span>${validDate($(id).value)?fmt($(id).value):'Chọn ngày'}</span><span class="calendaricon" aria-hidden="true">▦</span>`}}
function pickerRange(){return picker.target==='from'||picker.target==='to'?[$('from').value,$('to').value]:picker.target==='trendfrom'||picker.target==='trendto'?[$('trendfrom').value,$('trendto').value]:[$('caldate').value,$('caldate').value]}
function drawPicker(){const month=picker.month,first=`2026-${String(month+1).padStart(2,'0')}-01`,offset=dayIndex(first),start=add(first,-offset),last=add(`2026-${String(month+1).padStart(2,'0')}-01`,32),[a,b]=pickerRange();$('pickermonth').innerHTML=Array.from({length:12},(_,i)=>`<option value="${i}">Tháng ${i+1}</option>`).join('');$('pickermonth').value=String(month);$('monthprev').disabled=month===0;$('monthnext').disabled=month===11;$('pickermonthrange').hidden=picker.target==='caldate';let markup='<span class="weeknumber">Tuần</span>'+['T2','T3','T4','T5','T6','T7','CN'].map(n=>`<span class="pickerweekday">${n}</span>`).join('');const days=new Date(Date.UTC(2026,month+1,0)).getUTCDate(),rows=Math.ceil((days+offset)/7);for(let row=0;row<rows;row++){const monday=add(start,row*7),wi=weeks.findIndex(w=>monday>=w.from&&monday<=w.to);markup+=`<span class="pickerweek">T${wi+1}</span>`;for(let j=0;j<7;j++){const d=add(monday,j),active=validDate(d),same=d.slice(5,7)===first.slice(5,7),count=data?.records.filter(r=>r.from.slice(0,10)===d).length||0;markup+=`<button class="pickerday ${same?'':'adjacent'} ${d===$(picker.target).value?'chosen':''} ${d>=a&&d<=b?'inrange':''}" ${active?'':'disabled'} data-date="${d}" aria-label="${fmt(d)}, ${count} lượt đặt" aria-pressed="${d===$(picker.target).value}"><span>${Number(d.slice(8,10))}</span>${count?`<small>${count}</small>`:''}</button>`}}$('pickergrid').innerHTML=markup}
function openPicker(id){picker.target=id;picker.returnTo=$(id+'display');picker.month=validDate($(id).value)?Number($(id).value.slice(5,7))-1:9;$('pickertitle').textContent={from:'Chọn ngày bắt đầu',to:'Chọn ngày kết thúc',caldate:'Chọn ngày xem lịch',trendfrom:'Biểu đồ: ngày bắt đầu',trendto:'Biểu đồ: ngày kết thúc'}[id];drawPicker();$('calendarpicker').showModal()}
function chooseDate(d){if(!validDate(d))return;$(picker.target).value=d;$(picker.target).onchange?.();updateDateButtons();$('calendarpicker').close();picker.returnTo?.focus()}
for(const id of ['from','to','caldate','trendfrom','trendto'])$(id+'display').onclick=()=>openPicker(id);
$('pickerclose').onclick=()=>$('calendarpicker').close();$('pickermonth').onchange=()=>{picker.month=+$('pickermonth').value;drawPicker()};$('monthprev').onclick=()=>{picker.month=Math.max(0,picker.month-1);drawPicker()};$('monthnext').onclick=()=>{picker.month=Math.min(11,picker.month+1);drawPicker()};$('pickergrid').addEventListener('click',e=>{const b=e.target.closest('[data-date]');if(b)chooseDate(b.dataset.date)});$('pickertoday').onclick=()=>{const d=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());chooseDate(d)};$('pickermonthrange').onclick=()=>{const m=String(picker.month+1).padStart(2,'0'),start=`2026-${m}-01`,end=`2026-${m}-${new Date(Date.UTC(2026,picker.month+1,0)).getUTCDate()}`;const ids=picker.target.startsWith('trend')?['trendfrom','trendto']:['from','to'];$(ids[0]).value=start;$(ids[1]).value=end;$(ids[0]).onchange?.();updateDateButtons();$('calendarpicker').close()};
function normalizeTitle(title){return title.normalize('NFKC').toLocaleLowerCase('vi').trim().replace(/[\s:–—_\-]+/g,' ').replace(/[.,;]+$/,'').trim()}
function titleGroups(records){const map=new Map();for(const r of records){const key=normalizeTitle(r.title)||'không có tiêu đề';if(!map.has(key))map.set(key,{title:r.title||'Không có tiêu đề',records:[]});map.get(key).records.push(r)}return [...map.values()].sort((a,b)=>b.records.length-a.records.length||b.records.reduce((n,r)=>n+r.minutes,0)-a.records.reduce((n,r)=>n+r.minutes,0))}
function renderTitles(){const start=$('from').value,end=$('to').value,group=$('titlegroup').value,records=data.records.filter(r=>r.from.slice(0,10)>=start&&r.from.slice(0,10)<=end&&(!group||r.group===group));const totalMinutes=records.reduce((sum,r)=>sum+r.minutes,0),timeShare=x=>totalMinutes?x.records.reduce((sum,r)=>sum+r.minutes,0)/totalMinutes*100:0;const rows=titleGroups(records);$('titlecount').textContent=rows.length+' tiêu đề';const max=rows[0]?.records.length||0;$('titleinsight').innerHTML=max?`<span>Xuất hiện nhiều nhất</span><strong>${rows.filter(x=>x.records.length===max).map(x=>esc(x.title)).join(' · ')}</strong><p>${max} lượt cho mỗi tiêu đề${rows.filter(x=>x.records.length===max).length>1?' · đồng hạng':''}</p>`:'<p>Không có tiêu đề trong khoảng đã chọn.</p>';$('titleanalysis').innerHTML=rows.length?rows.map((x,i)=>`<tr><td><b>${esc(x.title)}</b><small class="titlevariants">${new Set(x.records.map(r=>r.title)).size>1?'Gộp '+new Set(x.records.map(r=>r.title)).size+' cách viết':''}</small></td><td>${x.records.length}</td><td><div class="sharebar"><span style="width:${timeShare(x)}%"></span></div>${number(timeShare(x))}%</td><td>${duration(x.records.reduce((n,r)=>n+r.minutes,0))}</td><td>${grouped(x.records).map(g=>esc(g.name)).join(', ')}</td></tr>`).join(''):'<tr><td colspan="5">Không có lịch phù hợp.</td></tr>';paginateTable('titleanalysis')}
function exportReport(){if(!data)return;const saved={...chartState};const model=chartData();if(model){chartState.start=model.fi;chartState.size=model.ti-model.fi+1}renderTrend();const main=document.querySelector('main').cloneNode(true);for(const id of ['summary','titleanalysis'])main.querySelector('#'+id).innerHTML=tablePages[id].rows.join('');main.querySelectorAll('.pagination').forEach(n=>n.remove());chartState=saved;renderTrend();main.querySelector('.introactions')?.remove();main.querySelector('.sync')?.remove();main.querySelector('#next')?.remove();main.querySelector('#error')?.remove();main.querySelectorAll('.zoomtools,.zoomhelp').forEach(x=>x.remove());main.querySelectorAll('[data-calendar]').forEach(button=>{const field=button.dataset.calendar;button.outerHTML=`<span class="reportvalue">${esc(fmt($(field).value))}</span>`});main.querySelectorAll('select').forEach(select=>{const source=$(select.id);select.outerHTML=`<span class="reportvalue">${esc(source.options[source.selectedIndex]?.text||'Tất cả nhóm')}</span>`});main.querySelectorAll('input[type=hidden]').forEach(x=>x.remove());main.querySelectorAll('#thismonth,#reset,#prevweek,#nextweek').forEach(x=>x.remove());main.querySelectorAll('details').forEach(d=>d.open=true);main.querySelectorAll('button').forEach(b=>{const span=document.createElement('div');span.className=b.className;span.innerHTML=b.innerHTML;const style=b.getAttribute('style');if(style)span.setAttribute('style',style);b.replaceWith(span)});main.querySelector('footer')?.remove();const records=[...data.records].sort((a,b)=>a.from.localeCompare(b.from));const appendix=document.createElement('section');appendix.className='panel exportappendix';appendix.innerHTML=`<h2>Phụ lục: toàn bộ ${records.length} lượt đặt phòng năm 2026</h2><p>Phần tổng quan phía trên giữ nguyên các bộ lọc đang xem. Phụ lục này liệt kê toàn bộ dữ liệu đã đồng bộ, để người nhận có đầy đủ thông tin.</p><table><thead><tr><th>Ngày / giờ / mã</th><th>Nhóm / người đặt / chủ trì</th><th>Tiêu đề / mô tả</th><th>Thời lượng / nhận diện</th></tr></thead><tbody>${records.map(r=>`<tr><td>${fmt(r.from)}<br>${r.from.slice(11,16)}–${r.to.slice(11,16)}<br><small>#${esc(r.id)}</small></td><td><b>${esc(r.group)}</b><br>Đặt: ${esc(r.booker||'Không ghi')}<br>Chủ trì: ${esc(r.host||'Không ghi')}</td><td><b>${esc(r.title)}</b><br>${esc(r.description||'Không có mô tả thêm')}</td><td>${duration(r.minutes)}<br><small>${esc(r.basis)}</small></td></tr>`).join('')}</tbody></table>`;main.appendChild(appendix);const now=new Date().toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'});const meta=document.createElement('p');meta.className='reportmeta';meta.textContent='Báo cáo Leipzig · Xuất lúc '+now+' (giờ Việt Nam) · Nguồn: '+data.source;main.prepend(meta);$('printreport').replaceChildren(main);document.title='Bao-cao-Leipzig-2026';window.print();document.title='Leipzig · Thống kê đặt phòng'}
$('exportpdf').onclick=exportReport;
for(const id of ['calgroup','barsgroup','summarygroup'])$(id).onchange=render;
$('trendgroup').onchange=renderTrend;$('titlegroup').onchange=renderTitles;

let busy=false,timer=null,nextAt=0;
function schedule(){clearTimeout(timer);nextAt=Date.now()+15000;timer=setTimeout(()=>{if(!document.hidden)sync();else schedule()},15000)}
async function sync(){if(busy)return;busy=true;$('refresh').disabled=true;$('refresh').textContent='Đang cập nhật…';$('syncstatus').textContent='Đang tải bản dữ liệu mới…';$('syncstatus').className='syncing';
 try{const response=await fetch('data.json',{cache:'no-store',signal:AbortSignal.timeout(55000)});if(!response.ok)throw new Error();const d=await response.json();d.stale=Date.now()-Date.parse(d.collectedAt)>20*60*1000;d.error=d.stale?'Dữ liệu đã hơn 20 phút chưa cập nhật. Kiểm tra GitHub Actions.':'';if(!Array.isArray(d.records))throw new Error();const first=!data;
 if(first||Date.parse(d.collectedAt)>=Date.parse(data.collectedAt))data=d;
 if(first)options();else refreshGroupOptions();
 const time=new Date(data.collectedAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'});$('update').textContent='Đồng bộ gần nhất: '+time+' (giờ Việt Nam)';$('source').href=data.source;
 $('syncstatus').textContent=d.stale?'Chưa đồng bộ được · giữ dữ liệu gần nhất':'Đã tải dữ liệu · kiểm tra mỗi 15 giây';$('syncstatus').className=d.stale?'stale':'connected';
 $('error').hidden=!d.stale;$('error').textContent=d.error||'';
 render();
 }catch{$('syncstatus').textContent='Mất kết nối · sẽ tự thử lại';$('syncstatus').className='stale';$('error').hidden=false;$('error').textContent=data?'Chưa lấy được dữ liệu mới. Dữ liệu gần nhất được giữ nguyên; trang sẽ thử lại sau 60 giây.':'Chưa kết nối được lịch UII. Trang sẽ tự thử lại sau 60 giây, hoặc bạn có thể bấm Cập nhật ngay.'}
 finally{busy=false;$('refresh').disabled=false;$('refresh').textContent='Cập nhật ngay';schedule()}}
if(data){options();render();const time=new Date(data.collectedAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'});$('update').textContent='Dữ liệu gần nhất: '+time+' (giờ Việt Nam)';}
$('refresh').onclick=sync;document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()>=nextAt)sync()});window.addEventListener('online',sync);
setInterval(()=>{$('next').textContent=busy?'Đang kiểm tra thay đổi…':document.hidden?'Tạm dừng khi trang ở nền':`Kiểm tra tiếp sau ${Math.max(0,Math.ceil((nextAt-Date.now())/1000))} giây`},1000);
sync();
